version: '3.8'

services:
  scraper:
    build: .
    container_name: web-scraper
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSISTANT_ID=${ASSISTANT_ID}
      - VECTOR_STORE_ID=${VECTOR_STORE_ID}
    restart: unless-stopped